export const techStack = [
  {
    title: "Version Control & Tools",
    items: [
      { name: "Git", icon: "https://skillicons.dev/icons?i=git" },
      { name: "GitHub", icon: "https://skillicons.dev/icons?i=github" },
      { name: "GitLab", icon: "https://skillicons.dev/icons?i=gitlab" },
      { name: "VSCode", icon: "https://skillicons.dev/icons?i=vscode" },
      { name: "Bun", icon: "https://skillicons.dev/icons?i=bun" },
      { name: "NPM", icon: "https://skillicons.dev/icons?i=npm" },
      { name: "PNPM", icon: "https://skillicons.dev/icons?i=pnpm" },
      { name: "Yarn", icon: "https://skillicons.dev/icons?i=yarn" },
      { name: "MySQL", icon: "https://skillicons.dev/icons?i=mysql" },
      { name: "PostgreSQL", icon: "https://skillicons.dev/icons?i=postgresql" },
      { name: "MongoDB", icon: "https://skillicons.dev/icons?i=mongodb" },
      { name: "Redis", icon: "https://skillicons.dev/icons?i=redis" },
      { name: "SQLite", icon: "https://skillicons.dev/icons?i=sqlite" },
    ],
  },
  {
    title: "Core Web Technologies",
    items: [
      { name: "HTML", icon: "https://skillicons.dev/icons?i=html" },
      { name: "CSS", icon: "https://skillicons.dev/icons?i=css" },
      { name: "JavaScript", icon: "https://skillicons.dev/icons?i=js" },
      { name: "TypeScript", icon: "https://skillicons.dev/icons?i=ts" },
      { name: "Python", icon: "https://skillicons.dev/icons?i=python" },
      { name: "PHP", icon: "https://skillicons.dev/icons?i=php" },
    ],
  },
  {
    title: "Frameworks & Libraries",
    items: [
      { name: "Express", icon: "https://skillicons.dev/icons?i=express" },
      { name: "Tailwind CSS", icon: "https://skillicons.dev/icons?i=tailwind" },
      { name: "Vite", icon: "https://skillicons.dev/icons?i=vite" },
      { name: "Vue.js", icon: "https://skillicons.dev/icons?i=vuejs" },
      { name: "Node.js", icon: "https://skillicons.dev/icons?i=nodejs" },
      { name: "NestJS", icon: "https://skillicons.dev/icons?i=nestjs" },
      { name: "Alpine.js", icon: "https://skillicons.dev/icons?i=alpinejs" },
      { name: "Laravel", icon: "https://skillicons.dev/icons?i=laravel" },
      { name: "Electron", icon: "https://skillicons.dev/icons?i=electron" },
      { name: "Nuxt", icon: "https://skillicons.dev/icons?i=nuxt" },
      { name: "Next.js", icon: "https://skillicons.dev/icons?i=nextjs" },
    ],
  },
];

export const projects = [
  {
    title: "GTNest - Gaming Marketplace",
    category: "Web Application",
    description:
      "GTNest is the ultimate marketplace for true gamers! Designed for the gaming community, GTNest offers a unique and engaging shopping experience, connecting enthusiasts with the gear, games, and accessories they love. More than just a platform, it's a vibrant hub where gamers can explore and elevate their gaming journey.",
    desktopImage: "/projects/gtnest-desktop.png",
    mobileImage: "/projects/gtnest-mobile.png",
    tags: ["Vue.js", "Laravel", "MySQL"],
    link: "https://gtnest.com",
    featured: true,
  },
  {
    title: "DramaBoss",
    category: "Web Application",
    description:
      "Dramaboss is a free online streaming platform offering a wide range of popular Chinese dramas sourced from Dramabox. Designed for an enjoyable and seamless viewing experience, it includes features such as:\n- **Full Episode Access**: Watch all episodes without subscriptions or payments.\n- **Trending & Popular Dramas**: Discover the latest and most popular dramas, regularly updated.\n- **Search Functionality**: Easily find your favorite dramas with an intuitive search feature.\n- **Diverse Categories**: Explore dramas by categories like romance, action, fantasy, and more.\nBuilt with modern technologies like **Vue.js** and **Vite**, Dramaboss provides a responsive and fast interface for both desktop and mobile devices. Visit [Dramaboss](https://dramaboss.online) to start watching your favorite Chinese dramas now!",
    desktopImage: "/projects/dramaboss-desktop.png",
    mobileImage: "/projects/dramaboss-mobile.png",
    tags: ["Nuxt", "MySQL"],
    link: "https://dramaboss.online",
    featured: true,
  },
  {
    title: "Haru no Sakuragi",
    category: "Landing Page",
    description:
      "A vibrant landing page for the Haru no Sakuragi event, showcasing event highlights and registration options.",
    desktopImage: "/projects/haru-desktop.png",
    mobileImage: "/projects/haru-mobile.png",
    tags: ["Vue.js", "Laravel", "MySQL"],
    link: "https://shiki.dvstproject.id/haru/",
    featured: false,
  },
  {
    title: "L'AMOR",
    category: "Web Application",
    description:
      "A web platform for L'AMOR, a drinking water service for the Riau community, providing service information and user management.",
    desktopImage: "/projects/lamor-desktop.png",
    mobileImage: "/projects/lamor-mobile.png",
    tags: ["Vue.js", "Vite", "Laravel", "MySQL"],
    link: "",
    featured: false,
  },
  {
    title: "Fuyu no Yukikaze",
    category: "Landing Page",
    description:
      "A visually appealing landing page for the Fuyu no Yukikaze event, featuring event details and registration functionality.",
    desktopImage: "/projects/fuyu-desktop.png",
    mobileImage: "/projects/fuyu-mobile.png",
    tags: ["Vue.js", "Laravel", "MySQL"],
    link: "https://shiki.dvstproject.id/fuyu/",
    featured: true,
  },
  {
    title: "Aki no Hajimari",
    category: "Landing Page",
    description:
      "A dynamic landing page for the Aki no Hajimari event, offering an interactive experience with event information and registration.",
    desktopImage: "/projects/aki-desktop.png",
    mobileImage: "/projects/aki-mobile.png",
    tags: ["Vue.js", "Laravel", "MySQL"],
    link: "https://shiki.dvstproject.id/aki/",
    featured: false,
  },
  {
    title: "Diversity Project",
    category: "Landing Page",
    description:
      "A professional landing page for Diversity Project, an event organizer, showcasing upcoming events, services, and many more.",
    desktopImage: "/projects/dvstproject-desktop.png",
    mobileImage: "/projects/dvstproject-mobile.png",
    tags: ["Wordpress", "PHP"],
    link: "https://dvstproject.id/",
    featured: false,
  },
  {
    title: "Arizona Marine Services",
    category: "Landing Page",
    description:
      "A modern landing page for Arizona Marine Services, highlighting marine-related services and expertise.",
    desktopImage: "/projects/ams-desktop.png",
    mobileImage: null,
    tags: ["Wordpress", "PHP"],
    link: "https://arizonamarineservices.com",
    featured: false,
  },
  {
    title: "Garuda Kencana Berdikari",
    category: "Landing Page",
    description:
      "A professional landing page for Garuda Kencana Berdikari, showcasing company services and information.",
    desktopImage: "/projects/gkb-desktop.png",
    mobileImage: null,
    tags: ["Wordpress", "PHP"],
    strikethrough: true,
    link: "",
    featured: false,
  },
  {
    title: "VALORANT Challengers ID 2021",
    category: "Web Application",
    description:
      "A comprehensive platform for the VALORANT Challengers Indonesia 2021, facilitating tournament organization, player management, and match tracking.",
    desktopImage: "/projects/vct2021-desktop.png",
    mobileImage: null,
    tags: ["Laravel", "PHP", "Vue.js", "MySQL"],
    link: "",
    featured: false,
  },
  {
    title: "SEA Icon Series ID 2021",
    category: "Web Application",
    description:
      "A dedicated platform for the SEA Icon Series Indonesia 2021, providing tools for managing esports tournaments, including participant registration, live updates, and leaderboards.",
    desktopImage: "/projects/seaicon-desktop.png",
    mobileImage: null,
    tags: ["Laravel", "PHP", "Vue.js", "MySQL"],
    link: "",
    featured: false,
  },
  {
    title: "MGA University Championship 2021",
    category: "Web Application",
    description:
      "An online platform for the MGA University Championship 2021, enabling tournament registration, match scheduling, and result tracking for university-level gaming competitions.",
    desktopImage: "/projects/mga-desktop.png",
    mobileImage: null,
    tags: ["Laravel", "PHP", "Vue.js", "MySQL"],
    link: "",
    featured: false,
  },
  {
    title: "Sistem Kehadiran Direktorat SMK",
    category: "Web Application",
    description:
      "A web-based attendance management system for the SMK Directorate, designed to streamline employee attendance tracking and reporting.",
    desktopImage: "/projects/simpeg-desktop.png",
    mobileImage: null,
    tags: ["Codeigniter4", "PHP", "MySQL"],
    link: "",
    featured: true,
  },
];
